insert into tags (id, name, color, user_id) values
  ('tg_fiction', 'Fiction', '#3b82f6', null),
  ('tg_nonfiction', 'Non-Fiction', '#10b981', null),
  ('tg_reviewcopy', 'Review Copy', '#8b5cf6', null),
  ('tg_mustread', 'Must Read', '#ef4444', null),
  ('tg_series', 'Series', '#f59e0b', null),
  ('tg_debut', 'Debut', '#84cc16', null),
  ('tg_friendstolovers', 'Friends to Lovers', '#6366f1', null),
  ('tg_enemiestolovers', 'Enemies to Lovers', '#ef4444', null),
  ('tg_fakerelationship', 'Fake Relationship', '#ec4899', null),
  ('tg_forcedproximity', 'Forced Proximity', '#8b5cf6', null),
  ('tg_secondchance', 'Second Chance', '#14b8a6', null),
  ('tg_lovetriangle', 'Love Triangle', '#f97316', null),
  ('tg_forbiddenlove', 'Forbidden Love', '#ef4444', null),
  ('tg_agegap', 'Age Gap', '#a855f7', null),
  ('tg_marriageofconvenience', 'Marriage of Convenience', '#06b6d4', null),
  ('tg_slowburn', 'Slow Burn', '#f59e0b', null),
  ('tg_loveatfirstsight', 'Love at First Sight', '#ec4899', null),
  ('tg_grumpysunshine', 'Grumpy/Sunshine', '#f59e0b', null),
  ('tg_secretbaby', 'Secret Baby', '#8b5cf6', null),
  ('tg_onebedtrope', 'One Bed', '#ec4899', null),
  ('tg_bestfriendssibling', 'Best Friend''s Sibling', '#6366f1', null),
  ('tg_officeromance', 'Office Romance', '#3b82f6', null),
  ('tg_smalltown', 'Small Town', '#84cc16', null),
  ('tg_billionaire', 'Billionaire', '#f59e0b', null),
  ('tg_royalty', 'Royalty', '#a855f7', null),
  ('tg_bodyguard', 'Bodyguard', '#ef4444', null),
  ('tg_singleparent', 'Single Parent', '#10b981', null),
  ('tg_nanny', 'Nanny', '#ec4899', null),
  ('tg_rivals', 'Rivals', '#ef4444', null),
  ('tg_opposites', 'Opposites Attract', '#f97316', null),
  ('tg_touchherwilldestroyyou', 'Touch Her & Die', '#ef4444', null),
  ('tg_secretidentity', 'Secret Identity', '#8b5cf6', null),
  ('tg_amnesia', 'Amnesia', '#6366f1', null),
  ('tg_soulmates', 'Soulmates', '#ec4899', null),
  ('tg_unrequitedlove', 'Unrequited Love', '#14b8a6', null),
  ('tg_lovestohateme', 'Loves to Hate Me', '#ef4444', null),
  ('tg_bedsharingforced', 'Forced Bed Sharing', '#ec4899', null),
  ('tg_marriagebeforeromance', 'Marriage Before Romance', '#06b6d4', null),
  ('tg_arranged', 'Arranged Marriage', '#a855f7', null),
  ('tg_mistaken', 'Mistaken Identity', '#6366f1', null),
  ('tg_protector', 'Protector', '#ef4444', null),
  ('tg_reunion', 'Reunion Romance', '#14b8a6', null),
  ('tg_belatedepiphany', 'Belated Love Epiphany', '#f97316', null),
  ('tg_playboy', 'Playboy Reformed', '#f59e0b', null),
  ('tg_wallflower', 'Wallflower', '#84cc16', null),
  ('tg_beautyandthebeast', 'Beauty and the Beast', '#8b5cf6', null),
  ('tg_damseldistress', 'Damsel in Distress', '#ec4899', null),
  ('tg_workingex', 'Working with the Ex', '#14b8a6', null),
  ('tg_longdistance', 'Long Distance', '#6366f1', null),
  ('tg_penpal', 'Pen Pals', '#3b82f6', null),
  ('tg_matchmaker', 'Matchmaker', '#ec4899', null),
  ('tg_timetravel', 'Time Travel', '#a855f7', null),

-- Fantasy Tropes
  ('tg_priceforwinning', 'Price for winning', '#3b82f6', null),
  ('tg_theprophecy', 'The prophecy', '#10b981', null),
  ('tg_pseudomedievalsettings', 'Pseudo-medieval settings', '#8b5cf6', null),
  ('tg_resurrection', 'Resurrection', '#ef4444', null),
  ('tg_timetravel', 'Time travel', '#f59e0b', null),
  ('tg_solvethepuzzle', 'Solve the puzzle', '#84cc16', null),
  ('tg_trainingmontages', 'Training montages', '#6366f1', null),
  ('tg_portaltoanotherworld', 'Portal to another world', '#ec4899', null),
  ('tg_societystoppedintime', 'Society stopped in time', '#14b8a6', null),
  ('tg_truenames', 'True names', '#f97316', null),
  ('tg_underaspell', 'Under a spell', '#06b6d4', null),
  ('tg_mythsandlegends', 'Myths and legends', '#a855f7', null),
  ('tg_herosjourney', 'Hero''s journey', '#3b82f6', null),
  ('tg_sidequests', 'Side quests', '#10b981', null),
  ('tg_sprawlinglibraries', 'Sprawling libraries', '#8b5cf6', null),
  ('tg_royalcourt', 'Royal court', '#ef4444', null),
  ('tg_kingdoms', 'Kingdoms', '#f59e0b', null),
  ('tg_secretlair', 'Secret lair', '#84cc16', null),
  ('tg_forbiddenforest', 'Forbidden forest', '#6366f1', null),
  ('tg_mysticalforest', 'Mystical forest', '#ec4899', null),
  ('tg_magiciansguild', 'Magicians guild', '#14b8a6', null),
  ('tg_thievesguild', 'Thieves'' guild', '#f97316', null),
  ('tg_taverns', 'Taverns', '#06b6d4', null),
  ('tg_floatingislands', 'Floating islands', '#a855f7', null),
  ('tg_darkcaves', 'Dark caves', '#3b82f6', null),
  ('tg_floatingcastles', 'Floating castles', '#10b981', null),
  ('tg_assassinsguild', 'Assassins guild', '#8b5cf6', null),
  ('tg_spaceships', 'Spaceships', '#ef4444', null),
  ('tg_theantihero', 'The antihero', '#f59e0b', null),
  ('tg_orphanhero', 'Orphan hero', '#84cc16', null),
  ('tg_reincarnatedfromthegods', 'Reincarnated from the gods', '#6366f1', null),
  ('tg_luckynovice', 'Lucky novice', '#ec4899', null),
  ('tg_lostheir', 'Lost heir', '#14b8a6', null),
  ('tg_heirtothethrone', 'Heir to the throne', '#f97316', null),
  ('tg_iwanttobetheverybestlikenooneeverwas', 'I want to be the very best (like no one ever was)', '#06b6d4', null),
  ('tg_patienceorlackthereof', 'Patience, or lack thereof', '#a855f7', null),
  ('tg_reluctanthero', 'Reluctant hero', '#3b82f6', null),
  ('tg_secretheir', 'Secret heir', '#10b981', null),
  ('tg_secretroyalty', 'Secret royalty', '#8b5cf6', null),
  ('tg_oldmanmentor', 'Old man mentor', '#ef4444', null),
  ('tg_ragstoriches', 'Rags to riches', '#f59e0b', null),
  ('tg_supremeruler', 'Supreme ruler', '#84cc16', null),
  ('tg_worldsworstspellcaster', 'World''s worst spellcaster', '#6366f1', null),
  ('tg_eviloverlord', 'Evil overlord', '#ec4899', null),
  ('tg_dualwielding', 'Dual wielding', '#14b8a6', null),
  ('tg_oldallies', 'Old allies', '#f97316', null),
  ('tg_evilrulers', 'Evil rulers', '#06b6d4', null),
  ('tg_thementor', 'The mentor', '#a855f7', null),
  ('tg_tavernowner', 'Tavern owner', '#3b82f6', null),
  ('tg_theparentalfigure', 'The parental figure', '#10b981', null),
  ('tg_thebard', 'The bard', '#8b5cf6', null),
  ('tg_goodwizardsandwitches', 'Good wizards and witches', '#ef4444', null),
  ('tg_outcasthero', 'Outcast hero', '#f59e0b', null),
  ('tg_theoutlaw', 'The outlaw', '#84cc16', null),
  ('tg_guardian', 'Guardian', '#6366f1', null),
  ('tg_darklord', 'Dark lord', '#ec4899', null),
  ('tg_nobility', 'Nobility', '#14b8a6', null),
  ('tg_swordsperson', 'Swordsperson', '#f97316', null),
  ('tg_magicwielder', 'Magic wielder', '#06b6d4', null),
  ('tg_evilwizardsandwitches', 'Evil wizards and witches', '#a855f7', null),
  ('tg_theloner', 'The loner', '#3b82f6', null),
  ('tg_shieldmaiden', 'Shield-maiden', '#10b981', null),
  ('tg_parentalfigure', 'Parental figure', '#8b5cf6', null),
  ('tg_damselsordudesindistress', 'Damsels or dudes in distress', '#ef4444', null),
  ('tg_kingsrighthandperson', 'King''s right-hand person', '#f59e0b', null),
  ('tg_thegoodsamaritan', 'The good Samaritan', '#84cc16', null),
  ('tg_assassins', 'Assassins', '#6366f1', null),
  ('tg_unlikelyallies', 'Unlikely allies', '#ec4899', null),
  ('tg_goodandevil', 'Good and evil', '#14b8a6', null),
  ('tg_quests', 'Quests', '#f97316', null),
  ('tg_godsandgoddesses', 'Gods and goddesses', '#06b6d4', null),
  ('tg_pointofnoreturn', 'Point of no return', '#a855f7', null),
  ('tg_secretknowledgelockedawayinanevenmoresecretlibrary', 'Secret knowledge locked away in an even more secret library', '#3b82f6', null),
  ('tg_pureevil', 'Pure evil', '#10b981', null),
  ('tg_comingofage', 'Coming of age', '#8b5cf6', null),
  ('tg_potions', 'Potions', '#ef4444', null),
  ('tg_finalshowdown', 'Final showdown', '#f59e0b', null),
  ('tg_ragstoriches77', 'Rags to riches', '#84cc16', null),
  ('tg_goodvsevil', 'Good vs. evil', '#6366f1', null),
  ('tg_discoveringonespowers', 'Discovering ones powers', '#ec4899', null),
  ('tg_acquiredsuperpowers', 'Acquired superpowers', '#14b8a6', null),
  ('tg_questforimmortality', 'Quest for immortality', '#f97316', null),
  ('tg_hellandheaven', 'Hell and heaven', '#06b6d4', null),
  ('tg_roadbackhome', 'Road back home', '#a855f7', null),
  ('tg_antagonistturnedallyredemptionarc', 'Antagonist turned ally – redemption arc', '#3b82f6', null),
  ('tg_reward', 'Reward', '#10b981', null),
  ('tg_thepricetopay', 'The price to pay', '#8b5cf6', null),
  ('tg_theeaglesthistropehasbeenpopularisedthroughlordoft', 'The eagles – this trope has been popularised through Lord of the Rings where the eagles swoop in and save Frodo and Sam at the last moment', '#ef4444', null),
  ('tg_thechosenone', 'The chosen one', '#f59e0b', null),
  ('tg_calltoadventure', 'Call to adventure', '#84cc16', null),
  ('tg_refusalofthecall', 'Refusal of the call', '#6366f1', null),
  ('tg_chosenone', 'Chosen one', '#ec4899', null),
  ('tg_rallythetroops', 'Rally the troops', '#14b8a6', null),
  ('tg_destroytheevilartifact', 'Destroy the evil artifact', '#f97316', null),
  ('tg_resurrection94', 'Resurrection', '#06b6d4', null),
  ('tg_enchantedsleep', 'Enchanted sleep', '#a855f7', null),
  ('tg_thenextadventureafteryourprotagonistcompletestheir', 'The next adventure – after your protagonist completes their quest, they''re itching for more', '#3b82f6', null),
  ('tg_royaltyjoinsthecrew', 'Royalty joins the crew', '#10b981', null),
  ('tg_magicrings', 'Magic rings', '#8b5cf6', null),
  ('tg_powerfulartifacts', 'Powerful artifacts', '#ef4444', null),
  ('tg_invisibilitycloaks', 'Invisibility cloaks', '#f59e0b', null),
  ('tg_magicpotions', 'Magic potions', '#84cc16', null),
  ('tg_sentientweapons', 'Sentient weapons', '#6366f1', null),
  ('tg_capesfordramaticimeanpracticalpurposes', 'Capes, for dramatic – I mean, practical – purposes', '#ec4899', null),
  ('tg_hiddentreasure', 'Hidden treasure', '#14b8a6', null),
  ('tg_magicswords', 'Magic swords', '#f97316', null),
  ('tg_bookofmagicspells', 'Book of magic spells', '#06b6d4', null),
  ('tg_wishmagic', 'Wish magic', '#a855f7', null),
  ('tg_healingmagic', 'Healing magic', '#3b82f6', null),
  ('tg_ancientmagic', 'Ancient magic', '#10b981', null),
  ('tg_blackmagic', 'Black magic', '#8b5cf6', null),
  ('tg_magicschools', 'Magic schools', '#ef4444', null),
  ('tg_alchemy', 'Alchemy', '#f59e0b', null),
  ('tg_naturemagic', 'Nature magic', '#84cc16', null),
  ('tg_necromancy', 'Necromancy', '#6366f1', null),
  ('tg_hiddenmagic', 'Hidden magic', '#ec4899', null),
  ('tg_forbiddenmagic', 'Forbidden magic', '#14b8a6', null),
  ('tg_dragons', 'Dragons', '#f97316', null),
  ('tg_moredragons', 'More dragons', '#06b6d4', null),
  ('tg_evenmoredragons', 'Even more dragons', '#a855f7', null),
  ('tg_giveusallthedragons', 'Give us all the dragons!', '#3b82f6', null),
  ('tg_darkelves', 'Dark elves', '#10b981', null),
  ('tg_elvesanddwarves', 'Elves and dwarves', '#8b5cf6', null),
  ('tg_demoniccreatures', 'Demonic creatures', '#ef4444', null),
  ('tg_halfling', 'Halfling', '#f59e0b', null),
  ('tg_faes', 'Faes', '#84cc16', null),
  ('tg_elves', 'Elves', '#6366f1', null),
  ('tg_trolls', 'Trolls', '#ec4899', null),
  ('tg_dwarves', 'Dwarves', '#14b8a6', null),
  ('tg_goblins', 'Goblins', '#f97316', null),
  ('tg_demons', 'Demons', '#06b6d4', null),
  ('tg_shapeshifting', 'Shapeshifting', '#a855f7', null),
  ('tg_guardiananimals', 'Guardian animals', '#3b82f6', null),
  ('tg_firebreathingdragons', 'Fire-breathing dragons', '#10b981', null),
  ('tg_unicorns', 'Unicorns', '#8b5cf6', null),
  ('tg_werewolves', 'Werewolves', '#ef4444', null),
  ('tg_vampires', 'Vampires', '#f59e0b', null),
  ('tg_legendarycreatures', 'Legendary creatures', '#84cc16', null),
  ('tg_monsters', 'Monsters', '#6366f1', null),
  ('tg_animalfamiliars', 'Animal familiars', '#ec4899', null),
  ('tg_fairygodmother', 'Fairy godmother', '#14b8a6', null),
  ('tg_animalguides', 'Animal guides', '#f97316', null),
  ('tg_horses', 'Horses', '#06b6d4', null),
  ('tg_gnomes', 'Gnomes', '#a855f7', null),
  ('tg_orcs', 'Orcs', '#3b82f6', null),
  ('tg_talkinganimals', 'Talking animals', '#10b981', null),
  ('tg_magicalcreatures', 'Magical creatures', '#8b5cf6', null),
  ('tg_fishoutofwater', 'Fish out of water', '#ef4444', null),
  ('tg_intergenerationaltrauma', 'Intergenerational trauma', '#f59e0b', null),
  ('tg_distractedbylove', 'Distracted by love', '#84cc16', null),
  ('tg_foundfamily', 'Found family', '#6366f1', null),
  ('tg_diplomaticmarriage', 'Diplomatic marriage', '#ec4899', null),
  ('tg_groupofmisfits', 'Group of misfits', '#14b8a6', null),
  ('tg_travellingparties', 'Travelling parties', '#f97316', null),
  ('tg_secretidentity', 'Secret identity', '#06b6d4', null),
  ('tg_misfits', 'Misfits', '#a855f7', null),
  ('tg_nextgeneration', 'Next generation', '#3b82f6', null)
on conflict (id) do nothing;
